player = obj_player;
player_x = player.x;
sprite_index = spr_nanami;
move = false;
instance_create_layer(player_x, 530, "Instances", textBox_obj);
instance_create_layer(player_x, 530, "Instances", nanamiText_obj);
instance_create_layer(player_x - 150, 60, "Instances", bcaWifi_obj);
textBox_obj.alarm[0] = 120;
nanamiText_obj.alarm[0] = 120;
player.alarm[1] = 120;