canAttack = false;
nextInteraction = 1500;
stepped = 0;
depth = -5;
vilOnScreen = false;
hasWifi = false;
hasPencil = false;
hasCleaning = false;
hasShower = false;
hasChem = false;
hasPolymorphisim = false;
hp = 200;
canMove =  true;
instance_create_layer(x + 5, y, "Instances", healthPlayer);
instance_create_layer(x, y - 5, "Instances", healthBarBorderPlayer_obj);
mrsenText1_obj.alarm[0] = 120;
textBox_obj.alarm[0] = 120;